import { DownloadIcon } from './icons.jsx';

export function DownloadCard({ agentName, path }) {
  const filename = path.split(/[\/\\]/).pop();
  return (
    <a
      href={`http://localhost:8000/download/${encodeURIComponent(agentName)}/${encodeURIComponent(filename)}`}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center justify-between bg-gray-800/60 border border-gray-700 rounded-xl p-4 hover:border-primary-500/50 hover:bg-gray-800 transition-colors"
    >
      <div className="flex items-center gap-3">
        <div className="p-2 bg-primary-600/15 text-primary-400 rounded-lg">
          <DownloadIcon />
        </div>
        <span className="text-sm font-medium text-gray-200">{filename}</span>
      </div>
      <span className="text-xs text-primary-400 font-semibold uppercase tracking-wider px-3 py-1 bg-primary-600/10 rounded-lg">Download</span>
    </a>
  );
}

export function DownloadList({ agentName, artifacts }) {
  return (
    <div className="space-y-3">
      <p className="text-sm text-gray-400 mb-4">The following artifacts were generated by {agentName}:</p>
      {artifacts.map((path, i) => (
        <DownloadCard key={i} agentName={agentName} path={path} />
      ))}
    </div>
  );
}
